name: domain-sync

on:
  # Deploy config whenever DNS changes are pushed to main.
  push:
    branches:
      - main
    paths:
      - '.github/workflows/domain-sync.yml'
      # Only domain folders ending in dots.
      - '*./*.yaml'
      - 'config.yaml'

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  publish:
    name: Publish DNS config from main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install pipenv
        run: pip install --user pipenv

      - name: Install octoDNS
        run: make setup

      - name: Publish
        run: make run
